### ISSUE TITLE
mingw64/sqlite3 CLI is broken, whilst msys/sqlite is fine

### ISSUE THREAD

**Issue by FrostKiwi** [msys2/MINGW-packages#10113]
I have `mingw64/mingw-w64-x86_64-sqlite3 3.36.0-1` installed. Using the sqlite3 CLI ( which is /mingw64/bin/sqlite3 ) to open and operate on databases does not work, as the CLI just gets stuck on the command line with cursor blinking and nothing more.
I also have `msys/sqlite 3.36.0-2` installed. Switching over to pure MSYS2 and modifying the database with the msys sqlite CLI tool ( which is /usr/bin/sqlite3 ) works just fine. The CLI properly initializes and I can modify SQLite databases.

As a workaround exists, this is pretty low-priority.

**Comment by Biswa96** [comment]
Can you provide an example of the command to reproduce your issue?

**Comment by FrostKiwi** [comment]
Just type sqlite3 into the command line of MSYS2-MinGW64. It just get's stuck with nothing happening.
Here is a video comparing how [LEFT] MSYS sqlite3 and [RIGHT] MinGW64 sqlite3 behave, one loads successfully, the other just get's stuck:

https://user-images.githubusercontent.com/60887273/142248797-7551c18d-e4cc-4de1-aec6-80462337a1c0.mp4

**Comment by lazka** [comment]
it needs a console, try `winpty sqlite3`

**Comment by FrostKiwi** [comment]
Ohh, that works! None of this is obvious though. Why do other CLI programs work, but specifically this one needs winpty?

**Comment by FrostKiwi** [comment]
Before I close this issue:

1. How can a user know if a console application can speak to the terminal or needs to be called with a separate console, eg. via TTY?
2. Why do some apps work with the terminal and sqlite3 does not? Why does mutt, nano etc. work but sqlite3 fails?
3. Should we create some kind of GitHub wiki entry or doc entry to explain this?

**Comment by FrostKiwi** [comment]
Well nvm. The issue is solved and I'm closing this.
There are overarching use-ability issue with MSYS in general when the different environments mix. Like msys cmake being called in the mingw64 environemnt, if mingw64 cmake is not present and leading to confusing errors like this one: https://github.com/rizsotto/Bear/issues/427
And the similarly here, MSYS sqlite working out of the box, but mingw64 cmake requiring a specific TTY emulator to run. Maybe I'll add a Wiki entry or something to address for MSYS newcomers like myself.

**Comment by lazka** [comment]
> Before I close this issue:
> 
>     1. How can a user know if a console application can speak to the terminal or needs to be called with a separate console, eg. via wintty?

Our default mode is that stdout is piped, which makes isatty() return false which some programs use to decide if they are interactive, like sqlite. Python also behaves the same, but we patch it to detect our terminal.

>     2. Why do some apps work with the terminal and sqlite3 does not? Why does mutt, nano etc. work but sqlite3 fails?

mutt/nano are cygwin tools, their isatty() returns the right value.

>     3. Should we create some kind of GitHub wiki entry or doc entry to explain this?

In theory cygwin, which we are based on has already solved this by "transparently" creating something winpty like when calling non-cygwin tools. Due to various bugs we haven'T enabled this by default in MSYS2 yet. We hope to do this at some point though.

**Comment by FrostKiwi** [comment]
@lazka Ohh, thanks for explaining!

**Comment by masoudd** [comment]
I have a similar problem and `winpty sqlite3` doesn't solve it for me. I found `sqlite3 | cat` does the trick. Currently looking deeper to find the root cause and hopefully fix it.

**Comment by Wolf-SO** [comment]
The original issue seems still be present in `UCRT64`, `CLANG64`, and `MINGW64`, while `MSYS` works. I was not able to find a binary `winpty` MSYS2 package, do I really have to build it from source?

Thanks, @masoudd, for your workaround!

**Comment by Wolf-SO** [comment]
I already started a discussion, maybe a better place for users to collect information:
[*Run sqlite3 CLI in UCRT64 (or MINGW64) environment*](https://github.com/msys2/MINGW-packages/discussions/24377 "Run sqlite3 CLI in UCRT64 (or MINGW64) environment · msys2/MINGW-packages · Discussion #24377")

**Comment by masoudd** [comment]
> I was not able to find a binary `winpty` MSYS2 package, do I really have to build it from source?

No. The regex is to exclude the python packages. Just do `-Ss winpty` and you'll find the winpty packages.
```
$ pacman -Ss -- ^winpty\|-winpty
clangarm64/mingw-w64-clang-aarch64-winpty 0.4.3-4
    A Windows software package providing an interface similar to a Unix pty-master for communicating
    with Windows console programs (mingw-w64)
mingw64/mingw-w64-x86_64-winpty 0.4.3-4
    A Windows software package providing an interface similar to a Unix pty-master for communicating
    with Windows console programs (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-winpty 0.4.3-4
    A Windows software package providing an interface similar to a Unix pty-master for communicating
    with Windows console programs (mingw-w64)
clang64/mingw-w64-clang-x86_64-winpty 0.4.3-4
    A Windows software package providing an interface similar to a Unix pty-master for communicating
    with Windows console programs (mingw-w64)
msys/winpty 0.4.3-3
    A Windows software package providing an interface similar to a Unix pty-master for communicating
    with Windows console programs

```

**Comment by Wolf-SO** [comment]
@masoudd Thanks for the help. I installed three of the packages for the environments that are relevant to me (UCRT64, CLANG64 and MINGW64), but after that there was no command named `winpty` available in any of them.

**Comment by masoudd** [comment]
> [@masoudd](https://github.com/masoudd) Thanks for the help. I installed three of the packages for the environments that are relevant to me (UCRT64, CLANG64 and MINGW64), but after that there was no command named `winpty` available in any of them.

Strange. Yes I tested and it seems only the `msys` package has a `winpty.exe` (`pacman -S winpty`). The packages for other environments lack it. Probably a bug

**Comment by Wolf-SO** [comment]
@masoudd Just to be sure: Should the packages be installed like `pacman -S mingw-w64-ucrt-x86_64-winpty`?

**Comment by masoudd** [comment]
> [@masoudd](https://github.com/masoudd) Just to be sure: Should the packages be installed like `pacman -S mingw-w64-ucrt-x86_64-winpty`?

Yes. for the UCRT environment, that is the correct package.
