### ISSUE TITLE
ld.exe: cannot find -lpython310: No such file or directory

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/MINGW-packages#13914]
### Description

I got an error when compiling a template rust-cpython project.

ld.exe: cannot find -lpython310: No such file or directory
          collect2.exe: error: ld returned 1 exit status

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19043.1110]

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

It got compiled successfully.

### Actual behavior

It returned an error for missing a library.

### Repro steps

1. install rust toolchain and maturin
2. run command 'maturin new -b rust-cpython rust-cpython' to create a template rust-cpython project
3. cd rust-cpython and run command 'maturin build' to build it

**Comment by ArchGuyWu** [comment]
I've confirmed that it exists in MSVC python.

**Comment by ArchGuyWu** [comment]
Should I report this to rust-cpython for handling posix-like library style?

**Comment by lazka** [comment]
Hard to say. Our Python is "special" in many ways, so anything hardcoded and not derived from information the Python installation itself provides (sysconfig etc) will likely result in errors.

If you have links/information to an example  rust-cpython project then we can have a look.

**Comment by MehdiChinoune** [comment]
I have encountered a similar issue before with python-cryptography and python-bcrypt.
I have disabled `abi3`
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-bcrypt/001-disable-abi3.patch
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-cryptography/001-disable-abi3.patch

Asked upstream in https://github.com/PyO3/pyo3/pull/1518

**Comment by lazka** [comment]
Maybe we can provide a abi3 build? I don't know much about it..

**Comment by ArchGuyWu** [comment]
I've reported this to rust-cpython, I did the same for maturin before.

**Comment by kmilos** [comment]
I recently ran across something similar when building OCIO bindings: Windows CPython (and its `python310.dll`) were being picked up before the MSYS2 Python - should be detecting and trying to link to `libpython3.10.dll` (in e.g. CMake based projects this is solved by passing the correct `-DPython_EXECUTABLE`/`-DPython3_EXECUTABLE`)

**Comment by lazka** [comment]
That's becaus cmake always prefers the installation it finds via the registry vs in the standard paths.. sadly.

**Comment by MehdiChinoune** [comment]
> > ld.exe: cannot find -lpython310: No such file or directory
> 
> I recently ran across something similar when building OCIO bindings: Windows (MSVC) CPython (and its `python310.dll`) were being picked up before the MSYS2 Python - should be detecting and trying to link to `libpython3.10.dll` instead (in e.g. CMake based projects this is solved by passing the correct `-DPython_EXECUTABLE`/`-DPython3_EXECUTABLE`)

That's a known issue.

**Comment by Rybec** [comment]
This bug still exists in the MINGW64 environment.  Discovered attempting to compile cryptography package.

**Comment by MehdiChinoune** [comment]
> This bug still exists in the MINGW64 environment. Discovered attempting to compile cryptography package.

cryptography package is available through pacman
```
pacman -S ${MINGW_PACKAGE_PREFIX}-python-cryptography
```
We patch it to make it build on MinGW-w64, see: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-cryptography

**Comment by Rybec** [comment]
Oh.  I looked for it but didn't see it.  That said, it was out of 700+ options, so I must has just missed it.  (I was also looking to see if there was a Python dev package, so I was a little distracted.)  I'll try that...seems to be working!  Thanks!

**Comment by lazka** [comment]
I've created an issue with our Python fork regarding abi3 here: https://github.com/msys2-contrib/cpython-mingw/issues/147

**Comment by lazka** [comment]
@Rybec the bug affecting cryptography has been fixed now.

To get back on topic here, I can confirm that this is currently still an issue:

```
  = note: C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpython311: No such file or directory
          collect2.exe: error: ld returned 1 exit status
```

it should use `-lpython3.11` there. I don't know where this is coming from, maybe https://github.com/dgrunwald/rust-cpython/blob/1402aaa1c71553bdfdbe1746f00b6e2096345e9e/python3-sys/build.rs#L250 ?

**Comment by lazka** [comment]
Since rust-cpython is superseded by pyo3, and this is implemented there https://github.com/PyO3/pyo3/blob/e4f0818fc29dcb8575da035422752c38bf46f68c/pyo3-build-config/src/impl_.rs#L1759-L1765 I'm closing this.
