### ISSUE TITLE
[luajit] Crashes on 32-bit builds

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#17042]
### Description / Steps to reproduce the issue

mpv CI started failing few days ago.
See https://github.com/mpv-player/mpv 

Example of crashing build https://github.com/mpv-player/mpv/actions/runs/4836193035/jobs/8619203629

It crashes during loading/executing lua scripts. Wasn't a problem few days ago as we can see on CI history.

Interestingly it is also not caused by recent luajit update, because I reverted this locally to older version and still crashes.

To reproduce:
`./mpv.com --no-config -v -v`

### Expected behavior

No crashes/exceptions

### Actual behavior

Crashes/exceptions

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The mpv package in mingw32 is working fine.

````
$ mpv.exe --no-config -v -v
[cplayer] Command line options: '--no-config' '-v' '-v'
[cplayer] mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Mar 14 07:20:51 2023
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.2.100
[cplayer]    libavcodec      60.3.100
[cplayer]    libavformat     60.3.100
[cplayer]    libswscale      7.1.100
[cplayer]    libavfilter     9.3.100
[cplayer]    libswresample   4.10.100
[cplayer] FFmpeg version: 6.0
[cplayer]
[cplayer] Configuration: meson configure build -Dprefix=/mingw32 -Dbuildtype=plain -Doptimization=plain
...
```

**Comment by kasper93** [comment]
```
mpv.com --no-config -v -v
```
So it works for you with OSD and everything?

**Comment by Biswa96** [comment]
I have ran the `./ci/build-msys2.sh meson` command in mingw32 and it works without any issue. That same command is ran in GitHub Actions workflow.

**Comment by Biswa96** [comment]
Wait a sec, I did not notice the return code. It's 127.

**Comment by Biswa96** [comment]
Replacing laujit with lua51 fixes the issue 🤔

**Comment by Biswa96** [comment]
Perfect, using debug build of luajit fixes the issue 🤦

**Comment by revelator** [comment]
if a debug build fixes it then it sounds like optimization is breaking something ?.
i've had problems using vector optimizations on 32 bit with some sources but i think this is enabled by default at -O2 so maybe we should try a lower optimization level for 32 bit.

**Comment by kasper93** [comment]
> if a debug build fixes it then it sounds like optimization is breaking something ?.
i've had problems using vector optimizations on 32 bit with some sources but i think this is enabled by default at -O2 so maybe we should try a lower optimization level for 32 bit.

Vector optimizations issues, cause by invalid stack alignment is GCC only bug (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412) and is patched in MSYS's provided GCC version. Clang is unaffected as it handles it properly.

For luajit, basically need to find the root cause why it crashes. I've seen that it panic on unwinding stack on error, but it shouldn't error out in the first place. And if optimization is breaking your software it is more likely that you have UB, compilers have pretty good test suites. Now mpv is using lua51 to make CI work again.

**Comment by lb90** [comment]
If I launch clang32\bin\mpv.exe from File Explorer I get the following "Procedure entry-point could not be located...":

```
vkCreateDisplayPlaneSurfaceKHR@16 in mpv.exe
vkGetInstanceProcAddr@8 in libplacebo-8.dll
```

So I guess that #17035 should fix this (with rebuilds of mpv and libplacebo)

**Comment by kasper93** [comment]
@lb90: Yes, it is #17029 what I did to test locally is to rename `C:\Windows\SysWOW64\vulkan-1.dll` temporarily to use the loader from msys sysroot which works.

**Comment by revelator** [comment]
ah vulkan loader problem then :)

**Comment by kasper93** [comment]
Wait, I think we misunderstood each other. luajit crashes are not related to Vulkan whatsoever. The only relation was that mpv was failing *also* when loading Vulkan, but the lua crash is still present.

**Comment by lb90** [comment]
The error is thrown from https://github.com/LuaJIT/LuaJIT/blob/224129a/src/lj_record.c#L2630. `op` is `BC_FNEW`

@kasper93 could you open an issue upstream?

**Comment by kasper93** [comment]
> @kasper93 could you open an issue upstream?

If it were upstream issue I would report it there in the first place. Upstream build works fine. Anyway I sent PR with the fix for the MSYS build.

**Comment by revelator** [comment]
the 32 bit unwinder is broken ?!? kinda defeats the purpose of a jit based build then doesnt it ?.
sounds like there is some issue we need to investigate with gcc then or does this also apply to clang ?.
