### ISSUE TITLE
Maybe someone forgot `-mwindows`?

### ISSUE THREAD

**Issue by iahung3** [msys2/MINGW-packages#20519]
### Description / Steps to reproduce the issue

`evince.exe` and `geany.exe` always come with a command prompt window

### Expected behavior

They are graphical application. There should be no command prompt window

### Actual behavior

There is always a command prompt window when open these applications

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No

**Comment by Kreijstal** [comment]
You can just call & at the end of the command

**Comment by Biswa96** [comment]
I have fixed this issue locally by adding `win_subsystem: 'windows'` in meson file and try to upstream the changes first.

**Comment by Biswa96** [comment]
This upstream pull request will fix the issue https://github.com/geany/geany/pull/3811

**Comment by ognevny** [comment]
> This upstream pull request will fix the issue https://github.com/geany/geany/pull/3811

I think you can backport it now. in case they don't accept just create the patch file with these change (or edit existing patch for meson.build)

**Comment by Biswa96** [comment]
> currently meson.build is patched to define `WIN32`

I meant to upstream the change first.

**Comment by iahung3** [comment]
@Biswa96 You forgot `evince.exe`: https://github.com/msys2/MINGW-packages/issues/19723 (console window popup), https://github.com/msys2/MINGW-packages/issues/20537 (missing icon). `gedit.exe` doesn't have a console window popup but it's also missing icon: https://github.com/msys2/MINGW-packages/issues/20526

**Comment by Biswa96** [comment]
See the comment in gedit thread. Those need more work in upstream.
