### ISSUE TITLE
[gnuplot] No visible prompt, hangs when displaying a plot

### ISSUE THREAD

**Issue by ProgMetalSlug** [msys2/MINGW-packages#8184]
If I start gnuplot in the mingw64 shell, there is no visible prompt. I can still type commands that seem to work correctly. However, If I try an plot something, the plot window hangs and says "Not Responding". I have to forcefully terminate gnuplot.

If I start gnuplot with "winpty gnuplot", there is no prompt either and I can't even type anything. I cannot even terminate gnuplot with Ctrl-C. I have to close the shell and terminate gnuplot from Windows' task manager.

I can run gnuplot scripts fine though.

**Comment by Biswa96** [comment]
Yes, this is an issue. The only thing that perfectly works is with `GNUTERM=sixel`. Need some debugging.

**Comment by bilderbuchi** [comment]
By now upstream has released gnuplot 5.4.2 - maybe an update would help ([current in msys is 5.4.1-3](https://packages.msys2.org/package/mingw-w64-x86_64-gnuplot), although there is this note:

> Note:
   There are known problems with running gnuplot 5.4 on Windows 10.
   At least one (failure of piped input to console) is still present
   in release 5.4.2.   Therefore you may prefer to stick with Windows
   binaries for the previous stable version, 5.2.8, until these issues
   are resolved in 5.4.

**Comment by gilgaTheDev** [comment]
I confirm that it's still a problem with the current version: the plot is shown but the window is not responding: you can't use the GUI buttons and you have to close the program forcefully.

**Comment by lukavilshyk** [comment]
Having the same problem as of June 2025.

**Comment by MehdiChinoune** [comment]
Should be fixed by #24511
